version: "3.7"
services:
  vue-intro:
    container_name: vue-intro
    build: .
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:/srv:rw
    ports:
      - ${SERVE_PORT-8080}:8080